### Assignment 14: Infinite Iterator

#Create an infinite iterator class named `InfiniteCounter` that starts from a given number and increments by 1 indefinitely. Test the iterator by printing the first 10 values generated by it.class InfiniteCounter:
class InfiniteCounter:
    def __init__(self, start):
        self.current = start

    def __iter__(self):
        return self

    def __next__(self):
        self.current += 1
        return self.current

# Test
counter = InfiniteCounter(0)
for _ in range(10):
     print(next(counter))